version: '2'
services:
  web:
    image: dockertest:0.0.1
    container_name: website
    hostname: dockertest
    ports:
      - "1000:3000"
    links:
      - "mysql:mysql"
    environment:
      - DATABASE_HOST=mysql
      - DB_USER=root
    networks:
      - network-name
  mysql:
    image: mysql
    container_name: mysql
    hostname: docker-mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlPassword
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    networks:
      - network-name
networks:
  network-name:
    driver: bridge